# Generated by Django 3.1.7 on 2021-07-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210722_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('mFrom', models.CharField(max_length=10)),
                ('mTo', models.CharField(max_length=10)),
                ('mDate', models.DateField(auto_now=True)),
                ('mTime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pgDetails',
            fields=[
                ('pgID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('floors', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=2000)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('total_intakes', models.IntegerField()),
                ('available_intakes', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('start_rent', models.IntegerField()),
                ('end_rent', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.owner')),
            ],
        ),
        migrations.CreateModel(
            name='roomDetails',
            fields=[
                ('roomID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('roomNo', models.IntegerField()),
                ('floorNo', models.IntegerField()),
                ('totalBed', models.IntegerField()),
                ('availableBed', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.FloatField(default=0.0)),
                ('ac', models.FloatField(default=0.0)),
                ('co', models.FloatField(default=0.0)),
                ('balcony', models.FloatField(default=0.0)),
                ('laundry', models.FloatField(default=0.0)),
                ('breakfast', models.FloatField(default=0.0)),
                ('lunch', models.FloatField(default=0.0)),
                ('dinner', models.FloatField(default=0.0)),
                ('parking', models.FloatField(default=0.0)),
                ('cleaning', models.FloatField(default=0.0)),
                ('wifi', models.FloatField(default=0.0)),
                ('tv', models.FloatField(default=0.0)),
                ('fridge', models.FloatField(default=0.0)),
                ('ro', models.FloatField(default=0.0)),
                ('gym', models.FloatField(default=0.0)),
                ('lift', models.FloatField(default=0.0)),
                ('generator', models.FloatField(default=0.0)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
            ],
        ),
        migrations.CreateModel(
            name='pgRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite', models.IntegerField()),
                ('haveClosingTime', models.BooleanField(default=True)),
                ('closingTime', models.TimeField(default='00:00:00')),
                ('visitors', models.BooleanField(default=False)),
                ('nonVeg', models.BooleanField(default=False)),
                ('oppositeGender', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking', models.BooleanField(default=False)),
                ('loudMusic', models.BooleanField(default=False)),
                ('party', models.BooleanField(default=False)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
            ],
        ),
        migrations.CreateModel(
            name='pgPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoPID', models.CharField(max_length=200)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
            ],
        ),
        migrations.CreateModel(
            name='pgFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('cleaning', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('ro', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
            ],
        ),
        migrations.CreateModel(
            name='applicationDetails',
            fields=[
                ('applicationID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sentDate', models.DateField(auto_now=True)),
                ('message', models.TextField(max_length=1000)),
                ('joiningDate', models.DateField()),
                ('approvedDate', models.DateField()),
                ('isApproved', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.owner')),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
        ),
    ]
