# Generated by Django 3.1.7 on 2021-07-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgrules',
            old_name='deposite',
            new_name='deposit',
        ),
        migrations.RemoveField(
            model_name='pgrules',
            name='closingTime',
        ),
    ]
