# Generated by Django 3.1.7 on 2021-07-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20210722_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgrules',
            name='pg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails'),
        ),
    ]
