# Generated by Django 3.1.7 on 2021-07-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_pgphotos_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgphotos',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails'),
        ),
    ]
