# Generated by Django 3.1.7 on 2021-07-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210722_1454'),
        ('owner', '0007_pgdetails_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appicationDate', models.DateField(auto_now=True)),
                ('appicationTime', models.TimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.owner')),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.pgdetails')),
            ],
        ),
    ]
