# Generated by Django 3.1.7 on 2021-07-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='isVarified',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='isVarified',
        ),
    ]
